### ISSUE TITLE
Just wanted to ask. .

### ISSUE THREAD

**Issue by aksr** [cykerway/ncmpy#1]
Hi Mr. Cukerway,

I just wanted to ask, are you planning to continue development on ncmpy?

**Comment by cykerway** [comment]
Hello, 

I'd like to if I have enough extra time. But I guess this is not the case in the near future...

The current `ncmpy` works, but is still a little bit messy in logic. I hope that I can make it clean in future release. Any refactoring by other people is welcome. The basic code is there, and the logic is there, so this is not a difficult job but requires some time.

**Comment by cykerway** [comment]
If you are still interested in it, good news is that a new version has been released.
