### ISSUE TITLE
Error with MPDClient

### ISSUE THREAD

**Issue by LZaaM** [cykerway/ncmpy#2]
after cloning the git i ran:

> sudo python2 setup.py install --prefix=/usr
> ncmpy

the application start and get killed instantly
this is the message i get right after...
[log.txt](https://github.com/cykerway/ncmpy/files/503940/log.txt)
I do not know much of python, can you help me ?

**Comment by LZaaM** [comment]
Ok, I uninstall python-mpd2 and everything work fine.
apparently it does not support "send_*" attribute.

**Comment by cykerway** [comment]
Older versions of ncmpy depend on python-mpd not python-mpd2. Their apis are not exactly the same.

Recently ncmpy has been ported to python3 and depends on python-mpd2 now.
