### ISSUE TITLE
install fails with output 1

### ISSUE THREAD

**Issue by connormcdermid** [cykerway/ncmpy#4]
cam-o@Archimedes:~$ pip install ncmpy
Collecting ncmpy
  Using cached https://files.pythonhosted.org/packages/9b/47/b3149780ba6c60f187c12cc812a7f2ee71a494394cacd7688697b64d5f29/ncmpy-1.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-X5Wq0B/ncmpy/setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-X5Wq0B/ncmpy/

**Comment by cykerway** [comment]
You are probably using Python 2, which is no longer maintained soon. Please switch to Python 3.

If this doesn't solve your problem feel free to reopen.
