### ISSUE TITLE
python-mpd2 3.0.1 is not working anymore

### ISSUE THREAD

**Issue by rmonico** [cykerway/ncmpy#6]
To install ncmpy I needed to change version of python-mpd2 to 1.0.0.

**Comment by cykerway** [comment]
Likely. The [doc](https://python-mpd2.readthedocs.io/en/latest/topics/getting-started.html) says the client can `send_idle()` but I didn't find this method in new version of `python-mpd2`. I'm not sure if the doc is still up to date. And I'm not interested in porting to the new version at this moment. I guess people wouldn't need multiple python mpd clients on their system, so keeping an old version of `python-mpd2` should be fine. If this is not true, they can install ncmpy in a virtual env. I added `python-mpd2==1.0.0` in `setup.py` so you can try a reinstall.
